import type { BodyType, Fuel, Transmission } from "@/db/schema";

/**
 * Estoque de demonstração.
 *
 * TEMPORÁRIO: existe para povoar um ambiente de teste e sai do código assim
 * que o teste terminar. Nada aqui é usado pelo produto.
 *
 * Os dados são plausíveis de propósito — preço coerente com o ano e a
 * quilometragem, versão que existe de verdade, placa nos dois formatos. Estoque
 * de mentira com números redondos e carros iguais esconde justamente os
 * problemas que a gente quer ver: alinhamento com preço de tamanhos
 * diferentes, filtro com marca única, ordenação com empate.
 */
export type DemoVehicle = {
  slug: string;
  brand: string;
  model: string;
  version: string;
  yearManufacture: number;
  yearModel: number;
  mileageKm: number;
  priceCents: number;
  transmission: Transmission;
  fuel: Fuel;
  bodyType: BodyType;
  color: string;
  doors: number;
  licensePlate: string;
  options: string[];
  description: string;
  featured: boolean;
  reserved?: boolean;
  /** Termos de busca da foto; o primeiro é sempre o modelo. */
  photoTags: string;
};

const OPCOES_BASE = ["ar_condicionado", "direcao_eletrica", "vidros_eletricos", "travas_eletricas"];
const OPCOES_COMPLETO = [
  ...OPCOES_BASE,
  "airbag",
  "abs",
  "central_multimidia",
  "camera_re",
  "sensor_estacionamento",
];

export const DEMO_STOCK: DemoVehicle[] = [
  {
    slug: "fiat-argo-drive-1-3-2023",
    brand: "Fiat",
    model: "Argo",
    version: "Drive 1.3 Firefly",
    yearManufacture: 2023,
    yearModel: 2023,
    mileageKm: 28400,
    priceCents: 7290000,
    transmission: "manual",
    fuel: "flex",
    bodyType: "hatch",
    color: "Branco",
    doors: 4,
    licensePlate: "RGP4A21",
    options: OPCOES_BASE,
    description:
      "Argo Drive 1.3 com revisões em dia e único dono. Econômico e fácil de estacionar, é a opção certa para quem roda na cidade todo dia.",
    featured: true,
    photoTags: "fiat,argo,hatch",
  },
  {
    slug: "fiat-toro-freedom-2022",
    brand: "Fiat",
    model: "Toro",
    version: "Freedom 1.8 AT6",
    yearManufacture: 2022,
    yearModel: 2022,
    mileageKm: 46500,
    priceCents: 12990000,
    transmission: "automatico",
    fuel: "flex",
    bodyType: "picape",
    color: "Cinza",
    doors: 4,
    licensePlate: "FTR7841",
    options: OPCOES_COMPLETO,
    description:
      "Picape Toro Freedom automática, com caçamba preservada e pneus novos. Cabe a família e cabe o serviço.",
    featured: true,
    photoTags: "fiat,toro,pickup",
  },
  {
    slug: "fiat-mobi-like-2021",
    brand: "Fiat",
    model: "Mobi",
    version: "Like 1.0",
    yearManufacture: 2021,
    yearModel: 2021,
    mileageKm: 52300,
    priceCents: 4590000,
    transmission: "manual",
    fuel: "flex",
    bodyType: "hatch",
    color: "Vermelho",
    doors: 4,
    licensePlate: "MOB2C77",
    options: OPCOES_BASE,
    description:
      "Mobi Like completo de fábrica para o segmento, com o menor custo de manutenção do pátio. Primeiro carro sem dor de cabeça.",
    featured: false,
    photoTags: "fiat,mobi,compact",
  },
  {
    slug: "volkswagen-polo-highline-2023",
    brand: "Volkswagen",
    model: "Polo",
    version: "Highline 200 TSI",
    yearManufacture: 2023,
    yearModel: 2023,
    mileageKm: 31900,
    priceCents: 9890000,
    transmission: "automatico",
    fuel: "flex",
    bodyType: "hatch",
    color: "Prata",
    doors: 4,
    licensePlate: "PLO9D14",
    options: OPCOES_COMPLETO,
    description:
      "Polo Highline turbo, com o acabamento mais completo da linha e central multimídia original. Dirige como carro de categoria acima.",
    featured: true,
    photoTags: "volkswagen,polo,hatchback",
  },
  {
    slug: "volkswagen-t-cross-comfortline-2022",
    brand: "Volkswagen",
    model: "T-Cross",
    version: "Comfortline 200 TSI",
    yearManufacture: 2022,
    yearModel: 2023,
    mileageKm: 41200,
    priceCents: 12890000,
    transmission: "automatico",
    fuel: "flex",
    bodyType: "suv",
    color: "Branco",
    doors: 4,
    licensePlate: "TCR5512",
    options: OPCOES_COMPLETO,
    description:
      "T-Cross Comfortline com porta-malas de 420 litros e assistentes de condução. SUV compacto que não abre mão de espaço.",
    featured: false,
    photoTags: "volkswagen,t-cross,suv",
  },
  {
    slug: "volkswagen-nivus-highline-2021",
    brand: "Volkswagen",
    model: "Nivus",
    version: "Highline 200 TSI",
    yearManufacture: 2021,
    yearModel: 2021,
    mileageKm: 58700,
    priceCents: 10990000,
    transmission: "automatico",
    fuel: "flex",
    bodyType: "suv",
    color: "Azul",
    doors: 4,
    licensePlate: "NVS3E88",
    options: OPCOES_COMPLETO,
    description:
      "Nivus Highline com teto em linha cupê e painel digital. Rodou pouco para o ano e está com garantia de fábrica vigente.",
    featured: false,
    photoTags: "volkswagen,nivus,crossover",
  },
  {
    slug: "chevrolet-onix-premier-2024",
    brand: "Chevrolet",
    model: "Onix",
    version: "Premier 1.0 Turbo",
    yearManufacture: 2024,
    yearModel: 2024,
    mileageKm: 18900,
    priceCents: 9299000,
    transmission: "automatico",
    fuel: "flex",
    bodyType: "hatch",
    color: "Preto",
    doors: 4,
    licensePlate: "ONX1F05",
    options: OPCOES_COMPLETO,
    description:
      "Onix Premier turbo praticamente novo, com pouco mais de 18 mil km. Seminovo com cara e cheiro de zero.",
    featured: true,
    photoTags: "chevrolet,onix,hatchback",
  },
  {
    slug: "chevrolet-tracker-ltz-2023",
    brand: "Chevrolet",
    model: "Tracker",
    version: "LTZ 1.0 Turbo",
    yearManufacture: 2023,
    yearModel: 2023,
    mileageKm: 34600,
    priceCents: 11990000,
    transmission: "automatico",
    fuel: "flex",
    bodyType: "suv",
    color: "Cinza",
    doors: 4,
    licensePlate: "TRK8827",
    options: OPCOES_COMPLETO,
    description:
      "Tracker LTZ com câmera de ré, sensores e ar-condicionado digital. SUV para quem quer altura sem perder economia.",
    featured: false,
    photoTags: "chevrolet,tracker,suv",
  },
  {
    slug: "chevrolet-s10-ltz-diesel-2021",
    brand: "Chevrolet",
    model: "S10",
    version: "LTZ 2.8 Diesel 4x4",
    yearManufacture: 2021,
    yearModel: 2021,
    mileageKm: 89400,
    priceCents: 18900000,
    transmission: "automatico",
    fuel: "diesel",
    bodyType: "picape",
    color: "Branco",
    doors: 4,
    licensePlate: "SDZ6G39",
    options: OPCOES_COMPLETO,
    description:
      "S10 LTZ diesel 4x4 com tração reduzida e capota marítima. Rodou estrada, e a manutenção está toda documentada.",
    featured: true,
    photoTags: "chevrolet,s10,pickup",
  },
  {
    slug: "hyundai-hb20-comfort-2022",
    brand: "Hyundai",
    model: "HB20",
    version: "Comfort 1.0",
    yearManufacture: 2022,
    yearModel: 2022,
    mileageKm: 44100,
    priceCents: 6890000,
    transmission: "manual",
    fuel: "flex",
    bodyType: "hatch",
    color: "Prata",
    doors: 4,
    licensePlate: "HBX4519",
    options: OPCOES_BASE,
    description:
      "HB20 Comfort com garantia de fábrica ainda válida. Manutenção barata e revenda fácil.",
    featured: false,
    photoTags: "hyundai,hb20,hatchback",
  },
  {
    slug: "hyundai-creta-platinum-2023",
    brand: "Hyundai",
    model: "Creta",
    version: "Platinum 2.0",
    yearManufacture: 2023,
    yearModel: 2023,
    mileageKm: 29700,
    priceCents: 14190000,
    transmission: "automatico",
    fuel: "flex",
    bodyType: "suv",
    color: "Azul",
    doors: 4,
    licensePlate: "CRT2H60",
    options: OPCOES_COMPLETO,
    description:
      "Creta Platinum com teto solar, bancos em couro e piloto automático adaptativo. O topo de linha do SUV mais vendido da marca.",
    featured: true,
    reserved: true,
    photoTags: "hyundai,creta,suv",
  },
  {
    slug: "toyota-corolla-altis-hybrid-2022",
    brand: "Toyota",
    model: "Corolla",
    version: "Altis Premium Hybrid",
    yearManufacture: 2022,
    yearModel: 2022,
    mileageKm: 52100,
    priceCents: 15490000,
    transmission: "cvt",
    fuel: "hibrido",
    bodyType: "sedan",
    color: "Preto",
    doors: 4,
    licensePlate: "CRL7J24",
    options: OPCOES_COMPLETO,
    description:
      "Corolla Altis híbrido, fazendo mais de 18 km/l na cidade. Conforto de sedã grande com consumo de carro pequeno.",
    featured: true,
    photoTags: "toyota,corolla,sedan",
  },
  {
    slug: "toyota-hilux-srv-2020",
    brand: "Toyota",
    model: "Hilux",
    version: "SRV 2.8 Diesel 4x4",
    yearManufacture: 2020,
    yearModel: 2020,
    mileageKm: 118500,
    priceCents: 17490000,
    transmission: "automatico",
    fuel: "diesel",
    bodyType: "picape",
    color: "Prata",
    doors: 4,
    licensePlate: "HLX9066",
    options: OPCOES_COMPLETO,
    description:
      "Hilux SRV diesel com histórico completo de revisões na concessionária. Picape que aguenta trabalho pesado e continua confortável.",
    featured: false,
    photoTags: "toyota,hilux,pickup",
  },
  {
    slug: "toyota-yaris-xls-2021",
    brand: "Toyota",
    model: "Yaris",
    version: "XLS 1.5 Connect",
    yearManufacture: 2021,
    yearModel: 2021,
    mileageKm: 61300,
    priceCents: 8590000,
    transmission: "cvt",
    fuel: "flex",
    bodyType: "sedan",
    color: "Branco",
    doors: 4,
    licensePlate: "YRS3K72",
    options: OPCOES_COMPLETO,
    description:
      "Yaris XLS sedã com sete airbags e central conectada. Robustez Toyota num pacote que cabe no orçamento.",
    featured: false,
    photoTags: "toyota,yaris,sedan",
  },
  {
    slug: "honda-civic-exl-2021",
    brand: "Honda",
    model: "Civic",
    version: "EXL 2.0 CVT",
    yearManufacture: 2021,
    yearModel: 2022,
    mileageKm: 47800,
    priceCents: 13590000,
    transmission: "cvt",
    fuel: "flex",
    bodyType: "sedan",
    color: "Cinza",
    doors: 4,
    licensePlate: "CVC5L18",
    options: OPCOES_COMPLETO,
    description:
      "Civic EXL com bancos em couro e sensor de ponto cego. Sedã que envelhece bem e não desvaloriza.",
    featured: false,
    photoTags: "honda,civic,sedan",
  },
  {
    slug: "honda-hr-v-exl-2022",
    brand: "Honda",
    model: "HR-V",
    version: "EXL 1.5 Turbo",
    yearManufacture: 2022,
    yearModel: 2023,
    mileageKm: 38200,
    priceCents: 14990000,
    transmission: "cvt",
    fuel: "flex",
    bodyType: "suv",
    color: "Prata",
    doors: 4,
    licensePlate: "HRV6M43",
    options: OPCOES_COMPLETO,
    description:
      "HR-V EXL turbo com bancos mágicos e porta-malas gigante para a categoria. SUV de família com espaço de verdade.",
    featured: true,
    photoTags: "honda,hrv,suv",
  },
  {
    slug: "jeep-compass-longitude-2024",
    brand: "Jeep",
    model: "Compass",
    version: "Longitude 1.3 T270",
    yearManufacture: 2024,
    yearModel: 2024,
    mileageKm: 22400,
    priceCents: 16990000,
    transmission: "automatico",
    fuel: "flex",
    bodyType: "suv",
    color: "Preto",
    doors: 4,
    licensePlate: "CMP1N29",
    options: OPCOES_COMPLETO,
    description:
      "Compass Longitude turbo com apenas 22 mil km e garantia de fábrica. SUV médio com acabamento de topo.",
    featured: true,
    photoTags: "jeep,compass,suv",
  },
  {
    slug: "jeep-renegade-sport-2021",
    brand: "Jeep",
    model: "Renegade",
    version: "Sport 1.8 AT6",
    yearManufacture: 2021,
    yearModel: 2021,
    mileageKm: 67900,
    priceCents: 9790000,
    transmission: "automatico",
    fuel: "flex",
    bodyType: "suv",
    color: "Verde",
    doors: 4,
    licensePlate: "RNG8P51",
    options: OPCOES_BASE,
    description:
      "Renegade Sport automático, com suspensão revisada e pneus novos. A porta de entrada da Jeep, no preço certo.",
    featured: false,
    photoTags: "jeep,renegade,suv",
  },
  {
    slug: "renault-kwid-intense-2023",
    brand: "Renault",
    model: "Kwid",
    version: "Intense 1.0",
    yearManufacture: 2023,
    yearModel: 2024,
    mileageKm: 15400,
    priceCents: 6790000,
    transmission: "manual",
    fuel: "flex",
    bodyType: "hatch",
    color: "Laranja",
    doors: 4,
    licensePlate: "KWD4Q06",
    options: OPCOES_BASE,
    description:
      "Kwid Intense quase zero, com 15 mil km rodados. O menor consumo do pátio e altura de SUV para as ruas ruins.",
    featured: false,
    photoTags: "renault,kwid,compact",
  },
  {
    slug: "renault-duster-iconic-2022",
    brand: "Renault",
    model: "Duster",
    version: "Iconic 1.3 Turbo CVT",
    yearManufacture: 2022,
    yearModel: 2022,
    mileageKm: 49800,
    priceCents: 10490000,
    transmission: "cvt",
    fuel: "flex",
    bodyType: "suv",
    color: "Marrom",
    doors: 4,
    licensePlate: "DST2R94",
    options: OPCOES_COMPLETO,
    description:
      "Duster Iconic turbo com o maior porta-malas da categoria. SUV que encara estrada de terra sem reclamar.",
    featured: false,
    reserved: true,
    photoTags: "renault,duster,suv",
  },
];
