import type { NewPlan } from "@/db/schema";

/**
 * Grade comercial inicial, transcrita da planilha.
 * É só o ponto de partida: depois de semeado, tudo é editável no Painel Geral.
 */
export const SEED_PLANS: NewPlan[] = [
  {
    name: "Start",
    slug: "start",
    description: "Para a loja que precisa do estoque no ar e os leads organizados.",
    priceCents: 29900,
    cycle: "MONTHLY",
    billingMode: "gateway",
    trialDays: 0,
    sortOrder: 1,
    highlighted: false,
    limits: { maxVehicles: 50, maxUsers: 2, maxStores: 1 },
    features: {
      gestao_estoque: true,
      preenchimento_automatico: true,
      avaliacao_veiculos: true,
      gestao_financiamentos: false,
      gerenciador_ofertas: true,
      site_automatico: true,
      hospedagem_manutencao: true,
      seo_tecnico: true,
      ga4_gtm: true,
      integracao_classificados: false,
      crm_leads: "basico",
      distribuicao_leads: false,
      funil_comercial: "basico",
      whatsapp_integrado: false,
      historico_conversas: false,
      origem_campanha: true,
      dashboards: "basico",
      gestao_multiunidade: false,
      permissoes_avancadas: false,
      api_webhooks: false,
      suporte: "digital",
    },
  },
  {
    name: "Performance",
    slug: "performance",
    description: "Para quem já vive de lead e precisa de funil e distribuição.",
    priceCents: 54900,
    cycle: "MONTHLY",
    billingMode: "gateway",
    trialDays: 0,
    sortOrder: 2,
    highlighted: true,
    limits: { maxVehicles: 100, maxUsers: 5, maxStores: 1 },
    features: {
      gestao_estoque: true,
      preenchimento_automatico: true,
      avaliacao_veiculos: true,
      gestao_financiamentos: true,
      gerenciador_ofertas: true,
      site_automatico: true,
      hospedagem_manutencao: true,
      seo_tecnico: true,
      ga4_gtm: true,
      integracao_classificados: true,
      crm_leads: "completo",
      distribuicao_leads: true,
      funil_comercial: "completo",
      whatsapp_integrado: true,
      historico_conversas: true,
      origem_campanha: true,
      dashboards: "completo",
      gestao_multiunidade: false,
      permissoes_avancadas: false,
      api_webhooks: false,
      suporte: "prioritario",
    },
  },
  {
    name: "Rede",
    slug: "rede",
    description: "Para grupo com mais de uma loja e time comercial estruturado.",
    priceCents: 99900,
    cycle: "MONTHLY",
    billingMode: "gateway",
    trialDays: 0,
    sortOrder: 3,
    highlighted: false,
    limits: { maxVehicles: 300, maxUsers: 15, maxStores: 3 },
    features: {
      gestao_estoque: true,
      preenchimento_automatico: true,
      avaliacao_veiculos: true,
      gestao_financiamentos: true,
      gerenciador_ofertas: true,
      site_automatico: true,
      hospedagem_manutencao: true,
      seo_tecnico: true,
      ga4_gtm: true,
      integracao_classificados: true,
      crm_leads: "completo",
      distribuicao_leads: true,
      funil_comercial: "completo",
      whatsapp_integrado: true,
      historico_conversas: true,
      origem_campanha: true,
      dashboards: "avancado",
      gestao_multiunidade: true,
      permissoes_avancadas: true,
      api_webhooks: true,
      suporte: "prioritario",
    },
  },
  {
    /**
     * Enterprise roda fora do gateway: preço sob negociação, cobrança por fora
     * e situação controlada na mão pelo Painel Geral.
     */
    name: "Enterprise",
    slug: "enterprise",
    description: "Sob negociação. Cobrança fora do gateway, limites combinados caso a caso.",
    priceCents: 0,
    cycle: "MONTHLY",
    billingMode: "manual",
    trialDays: 0,
    sortOrder: 4,
    highlighted: false,
    publicVisible: false,
    limits: { maxVehicles: null, maxUsers: null, maxStores: null },
    features: {
      gestao_estoque: true,
      preenchimento_automatico: true,
      avaliacao_veiculos: true,
      gestao_financiamentos: true,
      gerenciador_ofertas: true,
      site_automatico: true,
      hospedagem_manutencao: true,
      seo_tecnico: true,
      ga4_gtm: true,
      integracao_classificados: true,
      crm_leads: "completo",
      distribuicao_leads: true,
      funil_comercial: "completo",
      whatsapp_integrado: true,
      historico_conversas: true,
      origem_campanha: true,
      dashboards: "avancado",
      gestao_multiunidade: true,
      permissoes_avancadas: true,
      api_webhooks: true,
      suporte: "prioritario",
    },
  },
];
